variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  SOURCE: target/release/$CI_PROJECT_NAME
  DESTINATION: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_PROJECT_NAME/$CI_COMMIT_TAG/

build:
  stage: build
  image: rust:latest
  rules:
    - if: $CI_COMMIT_TAG
  cache:
    paths:
      - Cargo.lock
      - target
      - .cargo
  before_script:
    - cargo build --release
    - strip $SOURCE
  script:
    - >
      curl
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file $SOURCE $DESTINATION

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - >
      release-cli create
      --tag-name $CI_COMMIT_TAG
      --name "Release $CI_COMMIT_TAG"
      --description "Release $CI_COMMIT_TAG"
      --assets-link "{\"name\": \"$CI_PROJECT_NAME-$CI_COMMIT_TAG\", \"url\": \"$DESTINATION$CI_PROJECT_NAME\"}"
