---
stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: rust:latest
  script:
    - cargo build
  cache:
    paths:
      - Cargo.lock
      - target
  except:
    - master

test:
  stage: test
  image: rust:latest
  script:
    - cargo test
  cache:
    paths:
      - Cargo.lock
      - target
  dependencies:
    - build
  only:
    - dev


deploy:
  stage: deploy
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/pcoves/cleanup .
    - docker push registry.gitlab.com/pcoves/cleanup
  only:
    - master
