[package]
name = "cleanup"
version = "0.1.0"
authors = ["Pablo COVES <pablo.coves@anatoscope.com>"]
edition = "2018"
license = "WTFPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
either = "1.5.*"
rusoto_core = "0.43"
rusoto_credential = "0.43"
rusoto_ec2 = "0.43"
rusoto_sts = "0.43"
structopt = "0.2"
tini = "0.2"
tokio = "*"
