[package]
name = "cleanup"
version = "0.1.1"
authors = ["Pablo COVES <pablo.coves@anatoscope.com>"]
edition = "2018"
license = "MIT"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
dirs = "4"
either = "1"
futures = "0.3"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_ec2 = "0.47"
rusoto_sts = "0.47"
structopt = "0.3"
tini = "1"
tokio = {version = "1", features = ["full"] }
